### ISSUE TITLE
Swisspay API logic

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mercurylayer#101]
In the `query_lightning_payment` function in token-server/src/endpoints/token.rs#L265

Add logic to the swiss pay return structs (RTLInvoice and RTLQuery) to prevent an error when additional keys are returned in the json from the API. 

Like, e.g.:

```
2. Use #[serde(flatten)]
If you want to allow arbitrary additional fields without modifying your struct definition, you can add a HashMap<String, serde_json::Value> using the #[serde(flatten)] attribute. This will collect any extra fields into the map, enabling you to access them later if needed.

For example:

rust
Copy code
use serde::Deserialize;
use std::collections::HashMap;

#[derive(Deserialize, Debug)]
struct MyStruct {
    key1: String,
    #[serde(flatten)]
    extra: HashMap<String, serde_json::Value>, // Capture extra fields.
}

fn main() {
    let json_data = r#"{ "key1": "value1", "key2": 10, "extra_key": "extra_value" }"#;

    let parsed: MyStruct = serde_json::from_str(json_data).unwrap();
    println!("{:?}", parsed); // Output: MyStruct { key1: "value1", extra: {"key2": 10, "extra_key": "extra_value"} }
}
In this example, extra will contain all additional keys that are not explicitly defined in MyStruct.
```

Also, make all keys except for `isPaid` optional in the RTLQuery struct (as this is only one needed, and seems others can change). 

https://github.com/commerceblock/mercurylayer/blob/15a21adc5df79d4cd3ccaf6eac726988fd5227fa/token-server/src/endpoints/token.rs#L58

**Comment by ssantos21** [comment]
Implemented in https://github.com/commerceblock/mercurylayer/commit/a648e9f85be9d13bbfe5f9b0192fd291af4409e0
