### ISSUE TITLE
web site is down

### ISSUE THREAD

**Issue by jlopp** [commerceblock/mercurylayer#46]
FYI https://www.mercurylayer.com/ is offline

**Comment by nicosey** [comment]
thanks, we are migrating the website, will be back up soon...

**Comment by jlopp** [comment]
looks like it's down again

**Comment by tomt1664** [comment]
Are you getting an error. Seems not rendering properly on some browsers though. What browser are you using?

**Comment by jlopp** [comment]
I'm getting a DNS resolution error - no IP address found for domain.

**Comment by tomt1664** [comment]
Yes you are right www.mercurylayer.com is not configured (https://mercurylayer.com is). Will fix.
