### ISSUE TITLE
Reveals preimage if coin sent without batch_id

### ISSUE THREAD

**Issue by DhananjayPurohit** [commerceblock/mercurylayer#86]
If statecoin sender sends coin without batch_id the receiver should still be able to receive it, but no pre-image should be revealed.

This test should fail when trying to get the preimage but it's passing fine:-
https://github.com/commerceblock/mercurylayer/blob/feat/ln-latch-tests/clients/apps/nodejs/test/tb04-simple-lightning-latch.mjs#L473

**Comment by ssantos21** [comment]
It should fix this issue:
https://github.com/commerceblock/mercurylayer/commit/57727bdcade3d24a238281e03ec6bd1fbd417e47
