### ISSUE TITLE
Reconstruct backup transactions for verification

### ISSUE THREAD

**Issue by tomt1664** [commerceblock/mercurylayer#90]
To guard against *malicious transaction design* in ways that we may not be able to predict, the verification of each previous backup transaction should re-create the backup tx from the minimum data using the same tx construction used by the transfer-sender implementation. 

"by taking away the sender’s ability to give badly designed transactions in the first place, thus eliminating large classes of attacks which are dependent on the flexibility of input currently available to the statecoin sender."

For backwards compatibility (i.e. no changes made to the transfer process or transfer messages), the minimum data is extracted from each backup tx verified by the receiver:

A UTXO outpoint (input)
Locktime
Output amounts, and addresses

Then the same backup tx is reconstructed using the same functions as used in the client transfer-sender. The sighash is computed and check that it matches the sent backup tx and that the signature is valid. 

With this check - several of the existing transfer-receiver transaction checks are redundant and can be removed.

**Comment by ssantos21** [comment]
Implemented in https://github.com/commerceblock/mercurylayer/commit/7dbfc77b75cc72c8993def93c3fdc3185dc35bdf.
